# Exemplo de arquivo .streamlit/secrets.toml
# Copie este arquivo para .streamlit/secrets.toml e preencha com suas credenciais

[postgres]
host = "seu_host"
port = 5432
dbname = "seu_banco"
user = "seu_usuario"
password = "sua_senha"

# URL completa do banco de dados (será usada pela aplicação)
database_url = "postgresql://seu_usuario:sua_senha@seu_host:5432/seu_banco"
