# Example configuration file for local development
# Create a copy of this file as '.streamlit/secrets.toml' and fill in your database credentials

[postgres]
host = "your_database_host"  # e.g., "localhost" or your cloud database host
port = 5432  # default PostgreSQL port
dbname = "your_database_name"
user = "your_database_user"
password = "your_database_password"

# The complete database URL will be constructed using the above credentials
database_url = "postgresql://user:password@host:port/dbname"
